name: Deploy static site to Pages

on:
  push:
    branches: ["main"]  # 如果你用的是 master，改成 "master"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # ? 关键配置：指定你的网页文件夹路径
          path: './dist'  # 改成你实际的文件夹名称

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4